apiVersion: v1
kind: Secret
metadata:
  name: rclone-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{- range $key, $entry := .Values.configs -}}
  {{- if $entry -}}
  {{- $key | nindent 2 }}: "{{ $entry -}}"
    {{- end }}
  {{- end }}
